### ISSUE TITLE
Problem with angular 1.2.9?

### ISSUE THREAD

**Issue by ThCC** [m59peacemaker/angular-pmkr-components#1]
Is there any problem in using this version of AngularJS?

**Comment by m59peacemaker** [comment]
@ThCC Some of the current code the the components in this repo aren't supported in that version, but I'm going to push some changes soon that will make them work. 

Anyway, the error you're showing doesn't appear to be a problem with anything of mine. That's all `angular-route`.  Did you mean to post your issue somewhere else? If this was intended for me, what component are you using?

**Comment by ThCC** [comment]
Hi @m59peacemaker, thanks for replying so fast. 
I'm checking here and probably the error has nothing to do with your code. So I removed the publication referring to the error. 
But I wonder if your code works with version 1.2.9 of the AngularJS. It was my fault, I thought it was 1.2.0, but  it's 1.2.9, forgive me.

**Comment by m59peacemaker** [comment]
The only thing I can think of that isn't supported is `Validate Custom` because I used `$validators` that are only in the recent 1.3.0 beta-12+, I think. That was a bad design anyway. My updated code just uses `$setValidity` and works as far back as 1.2.0. When I get some tests written, I'll push the improved code.

**Comment by ThCC** [comment]
Okay. This time "will install your code" without being through the bower ... He updated the AngularJS and it was not something good... at all ...
Anything I will inform you.
Thanks and see ya

**Comment by m59peacemaker** [comment]
Yeah, this package has a very recent beta release of Angular as a dependency, so I think bower would prompt you to update Angular accordingly. Best to decline that! When I get my tests written, I'll test out different versions and rollback the dependency version.
