### ISSUE TITLE
Memoize filer.

### ISSUE THREAD

**Issue by Serhioromano** [m59peacemaker/angular-pmkr-components#2]
You have code like this.

```
var fromCache = cache[key];
if (fromCache) {
  return fromCache;
}
```

I think this will not work good if service(colback) that uses it return empty array. It will trigger that service again. The fact that there is nothing in cache[key] does not mean that this was never called before.

My be I am wrong.

**Comment by m59peacemaker** [comment]
@Serhioromano  oops! That was careless on my part. Empty arrays evaluate as truthy, but you are correct that I failed to handle cases where the function returns falsy values, like `''` or `null`, etc. I have pushed the correction.

```
    if (cache.hasOwnProperty(key)) {
      return cache[key];
    }
```

**Comment by Serhioromano** [comment]
Ok, good. I see ad61550d2d9e85deb56dcba01a886229bea9dd63.

Thank you. Good staff by the way.
