### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by RichardLitt** [m59peacemaker/angular-pmkr-components#3]
I can't find angular-pmkr-components on npm. Any reason it's not published there?

**Comment by m59peacemaker** [comment]
@RichardLitt I would publish it to bower, if anything. I'd rather not publish it until I at least finish writing tests. Leaving it as is is kind of my way of saying use with caution.

**Comment by RichardLitt** [comment]
Cool cool. Cheers.
